import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import {ThemeProvider} from "next-themes"

import Navbar from "@/app/universal_comp/Navbar"

import Sidebar from "@/app/reusable_comp/Sidebar"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
    
    <Navbar />
    
    <div className="flex flex-wrap shrink-0">
       <Sidebar />

{children}
    </div>
   

        </ThemeProvider>

      </body>
    </html>
  );
}
